namespace :legislation do

  desc "Creates legislation proposals for Pleno Abierto"
  task legislation_proposals: :environment do
    legislation_proposals = [
      { legislation_process_id: 26, author_id: 505793, proposal_type: "proposal", terms_of_service: "1",
        tag_list: "Acciones de creación y dinamización de la ESS en los ecosistemas territoriales",
        title: "Impulso de las Mesas de articulación de la ESS en cada ecosistema territorial a partir de los agentes que están operando en el distrito.",
        summary: "Esta medida pertenece a la línea de actuación: acciones de creación y dinamización de ESS en los ecosistemas territoriales.",
        description: "La Línea de actuación de esta acción pretende analizar y conocer las áreas territoriales y las necesidades que tiene la población para el desarrollo de los ecosistemas, e incorporar la ESS a las dinámicas de cada territorio tanto desde la promoción y apoyo de nuevas iniciativas (cubriendo las necesidades que se hayan detectado como no cubiertas), como desde el punto de vista de la demanda, dando a conocer la ESS entre los vecinos y las vecinas." },
      { legislation_process_id: 26, author_id: 505793, proposal_type: "proposal", terms_of_service: "1",
        tag_list: "Acciones de creación y dinamización de la ESS en los ecosistemas territoriales",
        title: "Realización de mapeos periódicos que incorporen iniciativas comunitarias existentes en cada territorio y servicios e infraestructuras disponibles activables a través de la cogestión público-social.",
        summary: "Esta medida pertenece a la línea de actuación: acciones de creación y dinamización de ESS en los ecosistemas territoriales.",
        description: "La Línea de actuación de esta acción pretende analizar y conocer las áreas territoriales y las necesidades que tiene la población para el desarrollo de los ecosistemas, e incorporar la ESS a las dinámicas de cada territorio tanto desde la promoción y apoyo de nuevas iniciativas (cubriendo las necesidades que se hayan detectado como no cubiertas), como desde el punto de vista de la demanda, dando a conocer la ESS entre los vecinos y las vecinas." },
      { legislation_process_id: 26, author_id: 505793, proposal_type: "proposal", terms_of_service: "1",
        tag_list: "Acciones de creación y dinamización de la ESS en los ecosistemas territoriales",
        title: "Realización de diagnósticos periódicos de necesidades en los ecosistemas territoriales para promover iniciativas de ESS en relación a las necesidades no cubiertas.",
        summary: "Esta medida pertenece a la línea de actuación: acciones de creación y dinamización de ESS en los ecosistemas territoriales.",
        description: "La Línea de actuación de esta acción pretende analizar y conocer las áreas territoriales y las necesidades que tiene la población para el desarrollo de los ecosistemas, e incorporar la ESS a las dinámicas de cada territorio tanto desde la promoción y apoyo de nuevas iniciativas (cubriendo las necesidades que se hayan detectado como no cubiertas), como desde el punto de vista de la demanda, dando a conocer la ESS entre los vecinos y las vecinas." },
      { legislation_process_id: 26, author_id: 505793, proposal_type: "proposal", terms_of_service: "1",
        tag_list: "Acciones de creación y dinamización de la ESS en los ecosistemas territoriales",
        title: "Realización de eventos de promoción de la ESS en los ecosistemas territoriales, dando presencia a la ESS tanto en los espacios ya constituidos no propios como apoyando los eventos específicos de ESS.",
        summary: "Esta medida pertenece a la línea de actuación: acciones de creación y dinamización de ESS en los ecosistemas territoriales.",
        description: "La Línea de actuación de esta acción pretende analizar y conocer las áreas territoriales y las necesidades que tiene la población para el desarrollo de los ecosistemas, e incorporar la ESS a las dinámicas de cada territorio tanto desde la promoción y apoyo de nuevas iniciativas (cubriendo las necesidades que se hayan detectado como no cubiertas), como desde el punto de vista de la demanda, dando a conocer la ESS entre los vecinos y las vecinas." },
      { legislation_process_id: 26, author_id: 505793, proposal_type: "proposal", terms_of_service: "1",
        tag_list: "Acciones de creación y dinamización de la ESS en los ecosistemas territoriales",
        title: "Sensibilización, formación y promoción en los territorios sobre consumo sostenible, cuidados, alimentación, finanzas, energía, vivienda, etc",
        summary: "Esta medida pertenece a la línea de actuación: acciones de creación y dinamización de ESS en los ecosistemas territoriales.",
        description: "La Línea de actuación de esta acción pretende analizar y conocer las áreas territoriales y las necesidades que tiene la población para el desarrollo de los ecosistemas, e incorporar la ESS a las dinámicas de cada territorio tanto desde la promoción y apoyo de nuevas iniciativas (cubriendo las necesidades que se hayan detectado como no cubiertas), como desde el punto de vista de la demanda, dando a conocer la ESS entre los vecinos y las vecinas." },
      { legislation_process_id: 26, author_id: 505793, proposal_type: "proposal", terms_of_service: "1",
        tag_list: "Acciones de creación y dinamización de la ESS en los ecosistemas territoriales",
        title: "Proyecto piloto: “Incorporación de la ESS a las comunidades de residentes de los edificios (propietarios/as e inquilinos/as)”. ",
        summary: "Esta medida pertenece a la línea de actuación: acciones de creación y dinamización de ESS en los ecosistemas territoriales.",
        description: "La Línea de actuación de esta acción pretende analizar y conocer las áreas territoriales y las necesidades que tiene la población para el desarrollo de los ecosistemas, e incorporar la ESS a las dinámicas de cada territorio tanto desde la promoción y apoyo de nuevas iniciativas (cubriendo las necesidades que se hayan detectado como no cubiertas), como desde el punto de vista de la demanda, dando a conocer la ESS entre los vecinos y las vecinas." },
      { legislation_process_id: 26, author_id: 505793, proposal_type: "proposal", terms_of_service: "1",
        tag_list: "Acciones de creación y dinamización de la ESS en los ecosistemas territoriales",
        title: "Proyecto piloto: “Estudio sobre las posibilidades de desarrollo de una moneda local y sobre su posible implantación en un marco restringido”.",
        summary: "Esta medida pertenece a la línea de actuación: acciones de creación y dinamización de ESS en los ecosistemas territoriales.",
        description: "La Línea de actuación de esta acción pretende analizar y conocer las áreas territoriales y las necesidades que tiene la población para el desarrollo de los ecosistemas, e incorporar la ESS a las dinámicas de cada territorio tanto desde la promoción y apoyo de nuevas iniciativas (cubriendo las necesidades que se hayan detectado como no cubiertas), como desde el punto de vista de la demanda, dando a conocer la ESS entre los vecinos y las vecinas." },
      { legislation_process_id: 26, author_id: 505793, proposal_type: "proposal", terms_of_service: "1",
        tag_list: "Acciones de creación y dinamización de la ESS en los ecosistemas territoriales",
        title: "Impulso de bancos de tiempo vinculados a iniciativas económicas ciudadanas.",
        summary: "Esta medida pertenece a la línea de actuación: acciones de creación y dinamización de ESS en los ecosistemas territoriales.",
        description: "La Línea de actuación de esta acción pretende analizar y conocer las áreas territoriales y las necesidades que tiene la población para el desarrollo de los ecosistemas, e incorporar la ESS a las dinámicas de cada territorio tanto desde la promoción y apoyo de nuevas iniciativas (cubriendo las necesidades que se hayan detectado como no cubiertas), como desde el punto de vista de la demanda, dando a conocer la ESS entre los vecinos y las vecinas." },
      { legislation_process_id: 26, author_id: 505793, proposal_type: "proposal", terms_of_service: "1",
        tag_list: "Acciones de creación y dinamización de la ESS en los ecosistemas territoriales",
        title: "Creación y desarrollo de tiendas-vivero en locales comerciales en desuso que funcionen a su vez como puntos de información hacia los vecinos y vecinas.",
        summary: "Esta medida pertenece a la línea de actuación: acciones de creación y dinamización de ESS en los ecosistemas territoriales.",
        description: "La Línea de actuación de esta acción pretende analizar y conocer las áreas territoriales y las necesidades que tiene la población para el desarrollo de los ecosistemas, e incorporar la ESS a las dinámicas de cada territorio tanto desde la promoción y apoyo de nuevas iniciativas (cubriendo las necesidades que se hayan detectado como no cubiertas), como desde el punto de vista de la demanda, dando a conocer la ESS entre los vecinos y las vecinas." },
      { legislation_process_id: 26, author_id: 505793, proposal_type: "proposal", terms_of_service: "1",
        tag_list: "Acciones de creación y dinamización de la ESS en los ecosistemas territoriales",
        title: "Facilitar el acceso de iniciativas de ESS a puestos de los mercados municipales a través de acuerdos con asociaciones empresariales de comerciantes.",
        summary: "Esta medida pertenece a la línea de actuación: acciones de creación y dinamización de ESS en los ecosistemas territoriales.",
        description: "La Línea de actuación de esta acción pretende analizar y conocer las áreas territoriales y las necesidades que tiene la población para el desarrollo de los ecosistemas, e incorporar la ESS a las dinámicas de cada territorio tanto desde la promoción y apoyo de nuevas iniciativas (cubriendo las necesidades que se hayan detectado como no cubiertas), como desde el punto de vista de la demanda, dando a conocer la ESS entre los vecinos y las vecinas." },
      { legislation_process_id: 26, author_id: 505793, proposal_type: "proposal", terms_of_service: "1",
        tag_list: "Acciones de creación y dinamización de la ESS en los ecosistemas territoriales",
        title: "Dotación de suelo público municipal para la  construcción y gestión de vivienda de protección pública a través de entidades de ESS.",
        summary: "Esta medida pertenece a la línea de actuación: acciones de creación y dinamización de ESS en los ecosistemas territoriales.",
        description: "La Línea de actuación de esta acción pretende analizar y conocer las áreas territoriales y las necesidades que tiene la población para el desarrollo de los ecosistemas, e incorporar la ESS a las dinámicas de cada territorio tanto desde la promoción y apoyo de nuevas iniciativas (cubriendo las necesidades que se hayan detectado como no cubiertas), como desde el punto de vista de la demanda, dando a conocer la ESS entre los vecinos y las vecinas." },
      { legislation_process_id: 26, author_id: 505793, proposal_type: "proposal", terms_of_service: "1",
        tag_list: "Acciones de creación y dinamización de la ESS en los ecosistemas territoriales",
        title: "Apertura de espacios públicos a las iniciativas de consumo sostenible, dando visibilidad a las impulsadas por las entidades de la ESS y, en general, del tejido local de los distritos.",
        summary: "Esta medida pertenece a la línea de actuación: acciones de creación y dinamización de ESS en los ecosistemas territoriales.",
        description: "La Línea de actuación de esta acción pretende analizar y conocer las áreas territoriales y las necesidades que tiene la población para el desarrollo de los ecosistemas, e incorporar la ESS a las dinámicas de cada territorio tanto desde la promoción y apoyo de nuevas iniciativas (cubriendo las necesidades que se hayan detectado como no cubiertas), como desde el punto de vista de la demanda, dando a conocer la ESS entre los vecinos y las vecinas." },
      { legislation_process_id: 26, author_id: 505793, proposal_type: "proposal", terms_of_service: "1",
        tag_list: "Sensibilización de la ESS en la educación formal",
        title: "Análisis de buenas prácticas de la ESS que puedan ser replicadas en los centros educativos.",
        summary: "Esta medida pertenece a la línea de actuación: sensibilización de la ESS en la educación formal.",
        description: "La Línea de actuación de esta acción pretende acercar la ESS a la educación formal (educación primaria, ESO, Bachillerato y FP) y proponer a los centros educativos la puesta en marcha de buenas prácticas y proyectos que la incorporen, en las que esté implicado el conjunto de la comunidad educativa." },
      { legislation_process_id: 26, author_id: 505793, proposal_type: "proposal", terms_of_service: "1",
        tag_list: "Sensibilización de la ESS en la educación formal",
        title: "Favorecer la sensibilización de las AMPAS y los centros educativos dando a conocer las iniciativas existentes de ESS. ",
        summary: "Esta medida pertenece a la línea de actuación: sensibilización de la ESS en la educación formal.",
        description: "La Línea de actuación de esta acción pretende acercar la ESS a la educación formal (educación primaria, ESO, Bachillerato y FP) y proponer a los centros educativos la puesta en marcha de buenas prácticas y proyectos que la incorporen, en las que esté implicado el conjunto de la comunidad educativa." },
      { legislation_process_id: 26, author_id: 505793, proposal_type: "proposal", terms_of_service: "1",
        tag_list: "Sensibilización de la ESS en la educación formal",
        title: "Puesta en marcha de cooperativas escolares como modelos de interacción para diseñar en las aulas.",
        summary: "Esta medida pertenece a la línea de actuación: sensibilización de la ESS en la educación formal.",
        description: "La Línea de actuación de esta acción pretende acercar la ESS a la educación formal (educación primaria, ESO, Bachillerato y FP) y proponer a los centros educativos la puesta en marcha de buenas prácticas y proyectos que la incorporen, en las que esté implicado el conjunto de la comunidad educativa." },
      { legislation_process_id: 26, author_id: 505793, proposal_type: "proposal", terms_of_service: "1",
        tag_list: "Sensibilización de la ESS en la educación formal",
        title: "Elaboración de materiales didácticos inspiradores sobre ESS para el profesorado y los centros educativos. ",
        summary: "Esta medida pertenece a la línea de actuación sensibilización de la ESS en la educación formal.",
        description: "La Línea de actuación de esta acción pretende acercar la ESS a la educación formal (educación primaria, ESO, Bachillerato y FP) y proponer a los centros educativos la puesta en marcha de buenas prácticas y proyectos que la incorporen, en las que esté implicado el conjunto de la comunidad educativa." },
      { legislation_process_id: 26, author_id: 505793, proposal_type: "proposal", terms_of_service: "1",
        tag_list: "Sensibilización de la ESS en la educación formal",
        title: "Incorporación de contenidos de ESS en el programa de formación anual del Instituto Municipal de Consumo.",
        summary: "Esta medida pertenece a la línea de actuación: sensibilización de la ESS en la educación formal.",
        description: "La Línea de actuación de esta acción pretende acercar la ESS a la educación formal (educación primaria, ESO, Bachillerato y FP) y proponer a los centros educativos la puesta en marcha de buenas prácticas y proyectos que la incorporen, en las que esté implicado el conjunto de la comunidad educativa." },
      { legislation_process_id: 26, author_id: 505793, proposal_type: "proposal", terms_of_service: "1",
        tag_list: "Apoyo a la inclusión para personas especialmente vulnerables en entidades de ESS",
        title: "Acciones de formación y acompañamiento a personas con dificultades de inserción para la creación de empresas de ESS, ya sean de carácter autogestionado o tuteladas (EI y CEE).",
        summary: "Esta medida pertenece a la línea de actuación: apoyo a la inclusión para personas especialmente vulnerables en entidades de ESS.",
        description: "La Línea de actuación de esta acción establece que la ESS es un instrumento muy valioso para la integración de personas con especiales dificultades de inserción laboral al mercado de trabajo, en la medida que sus iniciativas pueden contribuir a s incorporación directamente a través de sus entidades, además de favorecer la creación de nuevas iniciativas, ya sean éstas protegidas o no." },
      { legislation_process_id: 26, author_id: 505793, proposal_type: "proposal", terms_of_service: "1",
        tag_list: "Apoyo a la inclusión para personas especialmente vulnerables en entidades de ESS",
        title: "Proyectos pilotos de ESS con determinados colectivos con circunstancias especiales de inserción laboral que favorezcan la normalización de sus derechos laborales.",
        summary: "Esta medida pertenece a la línea de actuación: apoyo a la inclusión para personas especialmente vulnerables en entidades de ESS.",
        description: "La Línea de actuación de esta acción establece que la ESS es un instrumento muy valioso para la integración de personas con especiales dificultades de inserción laboral al mercado de trabajo, en la medida que sus iniciativas pueden contribuir a su incorporación directamente a través de sus entidades, además de favorecer la creación de nuevas iniciativas, ya sean éstas protegidas o no." },
      { legislation_process_id: 26, author_id: 505793, proposal_type: "proposal", terms_of_service: "1",
        tag_list: "Creación de un ámbito concreto para la investigación documentación innovación y transferencia de conocimiento en ESS",
        title: "Programa de formación específica para la promoción y gestión de la innovación en el seno de la ESS. ",
        summary: "Esta medida pertenece a la línea de actuación: creación de un ámbito concreto para la investigación, documentación, innovación y transferencia de conocimientos en ESS.",
        description: "La Línea de actuación de esta acción establece la creación y desarrollo de un ámbito específico coparticipado de la ESS dedicado a la investigación, la innovación y la trasferencia de conocimiento, abierto a distintos agentes de la innovación (centros ad hoc, universidades, grupos o personas expertas, entidades ciudadanas en procesos de elaboración de nuevas iniciativas, otras modalidades de empresas, etc.) y que permita asimismo poner en valor los elementos innovadores específicos de la ESS, en especial en cuanto a sus valores y sus características de organización y gestión." },
      { legislation_process_id: 26, author_id: 505793, proposal_type: "proposal", terms_of_service: "1",
        tag_list: "Creación de un ámbito concreto para la investigación documentación innovación y transferencia de conocimiento en ESS",
        title: "Ayuda a la financiación de entidades para promover procesos de innovación y para su incorporación en programas de ámbito estatal, europeo e internacional. ",
        summary: "Esta medida pertenece a la línea de actuación: creación de un ámbito concreto para la investigación, documentación, innovación y transferencia de conocimientos en ESS.",
        description: "La Línea de actuación de esta acción establece la creación y desarrollo de un ámbito específico coparticipado de la ESS dedicado a la investigación, la innovación y la trasferencia de conocimiento, abierto a distintos agentes de la innovación (centros ad hoc, universidades, grupos o personas expertas, entidades ciudadanas en procesos de elaboración de nuevas iniciativas, otras modalidades de empresas, etc.) y que permita asimismo poner en valor los elementos innovadores específicos de la ESS, en especial en cuanto a sus valores y sus características de organización y gestión." },
      { legislation_process_id: 26, author_id: 505793, proposal_type: "proposal", terms_of_service: "1",
        tag_list: "Creación de un ámbito concreto para la investigación documentación innovación y transferencia de conocimiento en ESS",
        title: "Apoyo en la mejora del proceso de desarrollo del Balance Social de la ESS como instrumento de alto valor para una organización empresarial innovadora.  ",
        summary: "Esta medida pertenece a la línea de actuación: creación de un ámbito concreto para la investigación, documentación, innovación y transferencia de conocimientos en ESS.",
        description: "La Línea de actuación de esta acción establece la creación y desarrollo de un ámbito específico coparticipado de la ESS dedicado a la investigación, la innovación y la trasferencia de conocimiento, abierto a distintos agentes de la innovación (centros ad hoc, universidades, grupos o personas expertas, entidades ciudadanas en procesos de elaboración de nuevas iniciativas, otras modalidades de empresas, etc.) y que permita asimismo poner en valor los elementos innovadores específicos de la ESS, en especial en cuanto a sus valores y sus características de organización y gestión." },
      { legislation_process_id: 26, author_id: 505793, proposal_type: "proposal", terms_of_service: "1",
        tag_list: "Convenios de colaboración con universidades centros de formación profesional y otros ámbitos de innovación para el desarrollo de iniciativas piloto de ESS",
        title: "Diseño y elaboración de proyectos de ESS para estudiantes de Universidad y Formación para el Empleo. ",
        summary: "Esta medida pertenece a la línea de actuación: convenios de colaboración con universidades, centros de formación profesional y otros ámbitos de innovación para el desarrollo de iniciativas piloto de ESS.",
        description: "La Línea de actuación de esta acción establece desarrollar marcos de colaboración para la difusión de la ESS entre los y las estudiantes de últimos ciclos y creación de incubadoras de proyectos de ESS en los ámbitos universitario y de formación profesional, bajo la concepción del aprender haciendo. Asegurar la presencia de la ESS en los espacios de innovación ya existentes." },
      { legislation_process_id: 26, author_id: 505793, proposal_type: "proposal", terms_of_service: "1",
        tag_list: "Convenios de colaboración con universidades centros de formación profesional y otros ámbitos de innovación para el desarrollo de iniciativas piloto de ESS",
        title: "Creación, en los ciclos finales de estudio, de bancos de proyectos para incubar, que alienten la creación de nuevas iniciativas de ESS.",
        summary: "Esta medida pertenece a la línea de actuación: convenios de colaboración con universidades, centros de formación profesional y otros ámbitos de innovación para el desarrollo de iniciativas piloto de ESS.",
        description: "La Línea de actuación de esta acción establece desarrollar marcos de colaboración para la difusión de la ESS entre los y las estudiantes de últimos ciclos y creación de incubadoras de proyectos de ESS en los ámbitos universitario y de formación profesional, bajo la concepción del aprender haciendo. Asegurar la presencia de la ESS en los espacios de innovación ya existentes." },
      { legislation_process_id: 26, author_id: 505793, proposal_type: "proposal", terms_of_service: "1",
        tag_list: "Convenios de colaboración con universidades centros de formación profesional y otros ámbitos de innovación para el desarrollo de iniciativas piloto de ESS",
        title: "Programa de incorporación de la ESS en los espacios de producción del conocimiento e innovación existentes a través de becas y pasantías de innovación para profesionales de la ESS.",
        summary: "Esta medida pertenece a la línea de actuación: convenios de colaboración con universidades, centros de formación profesional y otros ámbitos de innovación para el desarrollo de iniciativas piloto de ESS.",
        description: "La Línea de actuación de esta acción establece desarrollar marcos de colaboración para la difusión de la ESS entre los y las estudiantes de últimos ciclos y creación de incubadoras de proyectos de ESS en los ámbitos universitario y de formación profesional, bajo la concepción del aprender haciendo. Asegurar la presencia de la ESS en los espacios de innovación ya existentes." },
      { legislation_process_id: 26, author_id: 505793, proposal_type: "proposal", terms_of_service: "1",
        tag_list: "Convenios de colaboración con universidades centros de formación profesional y otros ámbitos de innovación para el desarrollo de iniciativas piloto de ESS",
        title: "Línea de becas y pasantías en entidades de la ESS para estudiantes de último ciclo, doctorandas/os y doctoradas/os.",
        summary: "Esta medida pertenece a la línea de actuación: convenios de colaboración con universidades, centros de formación profesional y otros ámbitos de innovación para el desarrollo de iniciativas piloto de ESS.",
        description: "La Línea de actuación de esta acción establece desarrollar marcos de colaboración para la difusión de la ESS entre los y las estudiantes de últimos ciclos y creación de incubadoras de proyectos de ESS en los ámbitos universitario y de formación profesional, bajo la concepción del aprender haciendo. Asegurar la presencia de la ESS en los espacios de innovación ya existentes." },
      { legislation_process_id: 26, author_id: 505793, proposal_type: "proposal", terms_of_service: "1",
        tag_list: "Convenios de colaboración con universidades centros de formación profesional y otros ámbitos de innovación para el desarrollo de iniciativas piloto de ESS",
        title: "Dotación de becas para la realización de postgrados universitarios con contenido de ESS o relacionados con ésta.",
        summary: "Esta medida pertenece a la línea de actuación: convenios de colaboración con universidades, centros de formación profesional y otros ámbitos de innovación para el desarrollo de iniciativas piloto de ESS.",
        description: "La Línea de actuación de esta acción establece desarrollar marcos de colaboración para la difusión de la ESS entre los y las estudiantes de últimos ciclos y creación de incubadoras de proyectos de ESS en los ámbitos universitario y de formación profesional, bajo la concepción del aprender haciendo. Asegurar la presencia de la ESS en los espacios de innovación ya existentes." },
      { legislation_process_id: 26, author_id: 505793, proposal_type: "proposal", terms_of_service: "1",
        tag_list: "Apoyo municipal a proyectos innovadores de alto impacto social",
        title: "Creación de un fondo público de inversión que adquiera parte de la propiedad de proyectos con alta posibilidad de ser escalables.",
        summary: "Esta medida pertenece a la línea de actuación: apoyo municipal a proyectos innovadores de alto impacto social.",
        description: "La Línea de actuación de esta acción establece fomentar el desarrollo de proyectos de ESS innovadores de alto impacto social, es decir, iniciativas que contribuyan a importantes cambios positivos y sostenibles en beneficio del entorno y la ciudadanía. Se trata, por una parte, de introducir a la ESS en nuevos ámbitos productivos, con capacidad para generar valor y, además, fomentar iniciativas con un alto compromiso respecto a la sostenibilidad social y ambiental y que contribuyan a mejorar significativamente las condiciones de vida de las personas involucradas. Ello contempla la posibilidad de apoyo cuando los procesos afronten dificultades especiales." },
      { legislation_process_id: 26, author_id: 505793, proposal_type: "proposal", terms_of_service: "1",
        tag_list: "Apoyo municipal a proyectos innovadores de alto impacto social",
        title: "Dotación de una partida presupuestaria dedicada a la financiación de proyectos de riesgo o de baja garantía a través de las fundaciones de banca ética y finanzas alternativas.",
        summary: "Esta medida pertenece a la línea de actuación: apoyo municipal a proyectos innovadores de alto impacto social.",
        description: "La Línea de actuación de esta acción establece fomentar el desarrollo de proyectos de ESS innovadores de alto impacto social, es decir, iniciativas que contribuyan a importantes cambios positivos y sostenibles en beneficio del entorno y la ciudadanía. Se trata, por una parte, de introducir a la ESS en nuevos ámbitos productivos, con capacidad para generar valor y, además, fomentar iniciativas con un alto compromiso respecto a la sostenibilidad social y ambiental y que contribuyan a mejorar significativamente las condiciones de vida de las personas involucradas. Ello contempla la posibilidad de apoyo cuando los procesos afronten dificultades especiales." },
      { legislation_process_id: 26, author_id: 505793, proposal_type: "proposal", terms_of_service: "1",
        tag_list: "Apoyo municipal a proyectos innovadores de alto impacto social",
        title: "Programa de apoyo a proyectos de alto impacto que tengan acogida entre donantes o inversores/as y que utilicen para financiarse las plataformas de financiación colectiva.",
        summary: "Esta medida pertenece a la línea de actuación: apoyo municipal a proyectos innovadores de alto impacto social.",
        description: "La Línea de actuación de esta acción establece fomentar el desarrollo de proyectos de ESS innovadores de alto impacto social, es decir, iniciativas que contribuyan a importantes cambios positivos y sostenibles en beneficio del entorno y la ciudadanía. Se trata, por una parte, de introducir a la ESS en nuevos ámbitos productivos, con capacidad para generar valor y, además, fomentar iniciativas con un alto compromiso respecto a la sostenibilidad social y ambiental y que contribuyan a mejorar significativamente las condiciones de vida de las personas involucradas. Ello contempla la posibilidad de apoyo cuando los procesos afronten dificultades especiales." },
      { legislation_process_id: 26, author_id: 505793, proposal_type: "proposal", terms_of_service: "1",
        tag_list: "Apoyo municipal a proyectos innovadores de alto impacto social",
        title: "Difusión y preparación para la participación de las entidades de ESS en el  programa de Compra Pública Innovadora.",
        summary: "Esta medida pertenece a la línea de actuación: apoyo municipal a proyectos innovadores de alto impacto social.",
        description: "La Línea de actuación de esta acción establece fomentar el desarrollo de proyectos de ESS innovadores de alto impacto social, es decir, iniciativas que contribuyan a importantes cambios positivos y sostenibles en beneficio del entorno y la ciudadanía. Se trata, por una parte, de introducir a la ESS en nuevos ámbitos productivos, con capacidad para generar valor y, además, fomentar iniciativas con un alto compromiso respecto a la sostenibilidad social y ambiental y que contribuyan a mejorar significativamente las condiciones de vida de las personas involucradas. Ello contempla la posibilidad de apoyo cuando los procesos afronten dificultades especiales." },
      { legislation_process_id: 26, author_id: 505793, proposal_type: "proposal", terms_of_service: "1",
        tag_list: "Economía social y solidaria: apoyo al desarrollo de entidades con alto valor tecnológico",
        title: "Programas de asistencia experta, sistemas de autodiagnóstico y asistencia tecnológica especializada paracreación y desarrollo de iniciativas, que faciliten la innovación en proyectos concretos.",
        summary: "Esta medida pertenece a la línea de actuación: economía social y solidaria: apoyo al desarrollo de entidades con alto valor tecnológico.",
        description: "La Línea de actuación de esta acción pretende contar con servicios de apoyo avanzados para la creación de empresas de ESS de base tecnológica, así como favorecer la mejora en este ámbito de las entidades ya existentes, fomentando igualmente el desarrollo de fomento de entidades de ESS en sectores estratégicos, desde apuestas colaborativas y contando con servicios de acompañamiento asistido entre entidades." },
      { legislation_process_id: 26, author_id: 505793, proposal_type: "proposal", terms_of_service: "1",
        tag_list: "Economía social y solidaria: apoyo al desarrollo de entidades con alto valor tecnológico",
        title: "Apoyo específico a empresas estratégicas de la ESS mediante el fomento de servicios avanzados de acompañamiento en ámbitos de alto valor dirigido a empresas tractoras y a potenciales empresas gacela.",
        summary: "Esta medida pertenece a la línea de actuación: economía social y solidaria: apoyo al desarrollo de entidades con alto valor tecnológico.",
        description: "La Línea de actuación de esta acción pretende contar con servicios de apoyo avanzados para la creación de empresas de ESS de base tecnológica, así como favorecer la mejora en este ámbito de las entidades ya existentes, fomentando igualmente el desarrollo de fomento de entidades de ESS en sectores estratégicos, desde apuestas colaborativas y contando con servicios de acompañamiento asistido entre entidades." },
      { legislation_process_id: 26, author_id: 505793, proposal_type: "proposal", terms_of_service: "1",
        tag_list: "Programa de formación y sensibilización en ESS para personal de servicios en el ámbito socioeconómico de la ciudad",
        title: "Campaña de sensibilización sobre ESS dirigida al personal municipal.",
        summary: "Esta medida pertenece a la línea de actuación: programa de formación y sensibilización en ESS para personal municipal de servicios en el ámbito socioeconómico de la ciudad.",
        description: "La Línea de actuación de esta acción pretende que el personal municipal conozca, comprenda y sea sensible a la estrategia de despliegue de la ESS en las políticas del Ayuntamiento. De tal forma que la ESS se vaya incorporando a la cultura municipal e impregne las políticas que se llevan a cabo desde las diferentes áreas de gobierno de la ciudad." },
      { legislation_process_id: 26, author_id: 505793, proposal_type: "proposal", terms_of_service: "1",
        tag_list: "Programa de formación y sensibilización en ESS para personal de servicios en el ámbito socioeconómico de la ciudad",
        title: "Formación específica sobre ESS en el marco de la oferta anual de formación continua que el Ayuntamiento ofrece a su personal. ",
        summary: "Esta medida pertenece a la línea de actuación: programa de formación y sensibilización en ESS para personal municipal de servicios en el ámbito socioeconómico de la ciudad.",
        description: "La Línea de actuación de esta acción pretende que el personal municipal conozca, comprenda y sea sensible a la estrategia de despliegue de la ESS en las políticas del Ayuntamiento. De tal forma que la ESS se vaya incorporando a la cultura municipal e impregne las políticas que se llevan a cabo desde las diferentes áreas de gobierno de la ciudad." },
      { legislation_process_id: 26, author_id: 505793, proposal_type: "proposal", terms_of_service: "1",
        tag_list: "Programa de formación y sensibilización en ESS para personal de servicios en el ámbito socioeconómico de la ciudad",
        title: "Difusión de la oferta formativa e informativa promovida por las entidades de ESS entre el personal municipal.",
        summary: "Esta medida pertenece a la línea de actuación: programa de formación y sensibilización en ESS para personal municipal de servicios en el ámbito socioeconómico de la ciudad.",
        description: "La Línea de actuación de esta acción pretende que el personal municipal conozca, comprenda y sea sensible a la estrategia de despliegue de la ESS en las políticas del Ayuntamiento. De tal forma que la ESS se vaya incorporando a la cultura municipal e impregne las políticas que se llevan a cabo desde las diferentes áreas de gobierno de la ciudad." },
      { legislation_process_id: 26, author_id: 505793, proposal_type: "proposal", terms_of_service: "1",
        tag_list: "Programa de formación en ESS dirigido a la ciudadanía que recibe atención en los recursos municipales para la inserción laboral",
        title: "Formación en ESS en los Talleres municipales de Formación e Inserción (TFIE).",
        summary: "Esta medida pertenece a la línea de actuación: programa de formación en ESS dirigido a la ciudadanía que recibe atención en los recursos municipales para la inserción laboral.",
        description: "La Línea de actuación de esta acción pretende generar espacios innovadores de formación dirigidos a toda la ciudadanía, con especial atención a las personas y los colectivos con mayores dificultades para la inserción sociolaboral, de acuerdo con los principios de equidad, trabajo y compromiso social, claves para el desarrollo de la ESS, contribuyendo a asegurar así que el desarrollo económico de la ciudad no deja fuera a nadie. Se incorporará a las acciones y planes formativos de la Agencia para el Empleo, así como de otros servicios municipales." },
      { legislation_process_id: 26, author_id: 505793, proposal_type: "proposal", terms_of_service: "1",
        tag_list: "Programa de formación en ESS dirigido a la ciudadanía que recibe atención en los recursos municipales para la inserción laboral",
        title: "Formación en ESS en programas específicos de diversas áreas municipales vinculadas con la atención, la promoción y el apoyo al empleo y la inserción.",
        summary: "Esta medida pertenece a la línea de actuación: programa de formación en ESS dirigido a la ciudadanía que recibe atención en los recursos municipales para la inserción laboral.",
        description: "La Línea de actuación de esta acción pretende generar espacios innovadores de formación dirigidos a toda la ciudadanía, con especial atención a las personas y los colectivos con mayores dificultades para la inserción sociolaboral, de acuerdo con los principios de equidad, trabajo y compromiso social, claves para el desarrollo de la ESS, contribuyendo a asegurar así que el desarrollo económico de la ciudad no deja fuera a nadie. Se incorporará a las acciones y planes formativos de la Agencia para el Empleo, así como de otros servicios municipales." },
      { legislation_process_id: 26, author_id: 505793, proposal_type: "proposal", terms_of_service: "1",
        tag_list: "Diseño de un programa de comunicación en torno a la ESS en el municipio",
        title: "Participación de la ESS e incorporación transversal de sus mensajes en eventos del Ayuntamiento.",
        summary: "Esta medida pertenece a la línea de actuación: diseño de un programa de comunicación en torno a la ESS en el municipio.",
        description: "La Línea de actuación de esta  acción establece el diseño de un programa específico de comunicación entorno a la ESS que contemple en su desarrollo acciones dirigidas a distintos ámbitos. Por una parte, el afianzamiento de las prácticas internas municipales que se concretan en esta estrategia para su divulgación activa entre la ciudadanía madrileña. Además, la construcción de un relato de la ciudad como ámbito que estimula la ESS, generando un proceso doble de identidad y pertenencia y favoreciendo el conocimiento de las actividades yrealizaciones de las entidades de la ESS en la ciudad de Madrid." },
      { legislation_process_id: 26, author_id: 505793, proposal_type: "proposal", terms_of_service: "1",
        tag_list: "Diseño de un programa de comunicación en torno a la ESS en el municipio",
        title: "Creación de lemas que visibilicen la ESS en el relato de ciudad que se transmite.",
        summary: "Esta medida pertenece a la línea de actuación: diseño de un programa de comunicación en torno a la ESS en el municipio.",
        description: "La Línea de actuación de esta acción establece el diseño de un programa específico de comunicación entorno a la ESS que contemple en su desarrollo acciones dirigidas a distintos ámbitos. Por una parte, el afianzamiento de las prácticas internas municipales que se concretan en esta estrategia para su divulgación activa entre la ciudadanía madrileña. Además, la construcción de un relato de la ciudad como ámbito que estimula la ESS, generando un proceso doble de identidad y pertenencia y favoreciendo el conocimiento de las actividades yrealizaciones de las entidades de la ESS en la ciudad de Madrid." },
      { legislation_process_id: 26, author_id: 505793, proposal_type: "proposal", terms_of_service: "1",
        tag_list: "Diseño de un programa de comunicación en torno a la ESS en el municipio",
        title: "Elaboración de un catálogo actualizado de las iniciativas existentes ofrecidas por la ESS que visibilice un conocimiento general y que facilite la labor de compra pública responsable.",
        summary: "Esta medida pertenece a la línea de actuación: diseño de un programa de comunicación en torno a la ESS en el municipio.",
        description: "La Línea de actuación de esta acción  establece el dDiseño de un programa específico de comunicación entorno a la ESS que contemple en su desarrollo acciones dirigidas a distintos ámbitos. Por una parte, el afianzamiento de las prácticas internas municipales que se concretan en esta estrategia para su divulgación activa entre la ciudadanía madrileña. Además, la construcción de un relato de la ciudad como ámbito que estimula la ESS, generando un proceso doble de identidad y pertenencia y favoreciendo el conocimiento de las actividades yrealizaciones de las entidades de la ESS en la ciudad de Madrid." },
      { legislation_process_id: 26, author_id: 505793, proposal_type: "proposal", terms_of_service: "1",
        tag_list: "Diseño de un programa de comunicación en torno a la ESS en el municipio",
        title: "Desarrollo de una Jornada anual de celebración de la ESS.",
        summary: "Esta medida pertenece a la línea de actuación: diseño de un programa de comunicación en torno a la ESS en el municipio.",
        description: "La Línea de actuación de esta acción establece el diseño de un programa específico de comunicación entorno a la ESS que contemple en su desarrollo acciones dirigidas a distintos ámbitos. Por una parte, el afianzamiento de las prácticas internas municipales que se concretan en esta estrategia para su divulgación activa entre la ciudadanía madrileña. Además, la construcción de un relato de la ciudad como ámbito que estimula la ESS, generando un proceso doble de identidad y pertenencia y favoreciendo el conocimiento de las actividades yrealizaciones de las entidades de la ESS en la ciudad de Madrid." },
      { legislation_process_id: 26, author_id: 505793, proposal_type: "proposal", terms_of_service: "1",
        tag_list: "Diseño de un programa de comunicación en torno a la ESS en el municipio",
        title: "Apoyo a la visibilización de los eventos propios de las organizaciones representativas de la ESS.",
        summary: "Esta medida pertenece a la línea de actuación: diseño de un programa de comunicación en torno a la ESS en el municipio.",
        description: "La Línea de actuación de esta acción  establece el diseño de un programa específico de comunicación entorno a la ESS que contemple en su desarrollo acciones dirigidas a distintos ámbitos. Por una parte, el afianzamiento de las prácticas internas municipales que se concretan en esta estrategia para su divulgación activa entre la ciudadanía madrileña. Además, la construcción de un relato de la ciudad como ámbito que estimula la ESS, generando un proceso doble de identidad y pertenencia y favoreciendo el conocimiento de las actividades yrealizaciones de las entidades de la ESS en la ciudad de Madrid." },
      { legislation_process_id: 26, author_id: 505793, proposal_type: "proposal", terms_of_service: "1",
        tag_list: "Contratación y compra pública responsable",
        title: "Definición y desarrollo de acciones de análisis y mejora de aplicación de cláusulas sociales/medioambientales en ámbito de ESS, y acciones de conocimiento y difusión de buenas prácticas para Madrid",
        summary: "Esta medida pertenece a la línea de actuación: contratación y compra pública responsable.",
        description: "La Línea de actuación de esta acción establece la Incorporación en las prácticas del Ayuntamiento de la contratación y la compra pública responsable, actuando de manera ejemplarizante y asumiendo su papel decisivo en la transformación del modelo económico de la ciudad, dada su importancia como ente consumidor y como contraparte de multitud de contratos con empresas y entidades de la sociedad civil en la prestación de servicios a la ciudadanía." },
      { legislation_process_id: 26, author_id: 505793, proposal_type: "proposal", terms_of_service: "1",
        tag_list: "Contratación y compra pública responsable",
        title: "Seguimiento periódico y valoración del impacto de la aplicación de las cláusulas sociales y medioambientales en el desarrollo de la ESS. ",
        summary: "Esta medida pertenece a la línea de actuación: contratación y compra pública responsable.",
        description: "La Línea de actuación de esta acción establece la Incorporación en las prácticas del Ayuntamiento de la contratación y la compra pública responsable, actuando de manera ejemplarizante y asumiendo su papel decisivo en la transformación del modelo económico de la ciudad, dada su importancia como ente consumidor y como contraparte de multitud de contratos con empresas y entidades de la sociedad civil en la prestación de servicios a la ciudadanía." },
      { legislation_process_id: 26, author_id: 505793, proposal_type: "proposal", terms_of_service: "1",
        tag_list: "Contratación y compra pública responsable",
        title: "Creación de un grupo de trabajo específico para generar oferta ligada a la reserva de mercado, en especial para EI y CEE cuyas entidades promotoras sean entidades sin ánimo de lucro.",
        summary: "Esta medida pertenece a la línea de actuación: contratación y compra pública responsable.",
        description: "La Línea de actuación de esta acción establece la Incorporación en las prácticas del Ayuntamiento de la contratación y la compra pública responsable, actuando de manera ejemplarizante y asumiendo su papel decisivo en la transformación del modelo económico de la ciudad, dada su importancia como ente consumidor y como contraparte de multitud de contratos con empresas y entidades de la sociedad civil en la prestación de servicios a la ciudadanía." },
      { legislation_process_id: 26, author_id: 505793, proposal_type: "proposal", terms_of_service: "1",
        tag_list: "Contratación y compra pública responsable",
        title: "Puesta en marcha de mecanismos de observación sobre la participación de CEE y EI en la contratación municipal. ",
        summary: "Esta medida pertenece a la línea de actuación: contratación y compra pública responsable.",
        description: "La Línea de actuación de esta acción establece la Incorporación en las prácticas del Ayuntamiento de la contratación y la compra pública responsable, actuando de manera ejemplarizante y asumiendo su papel decisivo en la transformación del modelo económico de la ciudad, dada su importancia como ente consumidor y como contraparte de multitud de contratos con empresas y entidades de la sociedad civil en la prestación de servicios a la ciudadanía." },
      { legislation_process_id: 26, author_id: 505793, proposal_type: "proposal", terms_of_service: "1",
        tag_list: "Programa de formación permanente y fortalecimiento para mejorar el desarrollo de las entidades de ESS",
        title: "Apoyo a las acciones formativas promovidas por las entidades de la ESS.",
        summary: "Esta medida pertenece a la línea de actuación: programa de formación permanente y fortalecimiento para mejorar el desarrollo de las entidades de ESS.",
        description: "La Línea de actuación de esta acción establece fortalecer las capacidades técnicas, operativas y estratégicas de las entidades de la ESS para mejorar su competitividad y posicionamiento. Para ello, se establecen acciones que contribuyen a la gestión y trasferencia de conocimiento entre las entidades, la mejora de las situaciones de las entidades en situación de crisis y la dotación de programas de aprendizaje abiertos y multidisciplinares que resuelvan las necesidades crecientes de la ESS. Es especialmente importante favorecer con estas acciones la incorporación efectiva de las mujeres en todos los niveles de la ESS, así como el apoyo a las iniciativas mayoritariamente conformadas por mujeres." },
      { legislation_process_id: 26, author_id: 505793, proposal_type: "proposal", terms_of_service: "1",
        tag_list: "Programa de formación permanente y fortalecimiento para mejorar el desarrollo de las entidades de ESS",
        title: "Apoyo a los procesos de internacionalización y/o de asentamiento en otros territorios del Estado. ",
        summary: "Esta medida pertenece a la línea de actuación: programa de formación permanente y fortalecimiento para mejorar el desarrollo de las entidades de ESS.",
        description: "La Línea de actuación de esta acción  establece fortalecer las capacidades técnicas, operativas y estratégicas de las entidades de la ESS para mejorar su competitividad y posicionamiento. Para ello, se establecen acciones que contribuyen a la gestión y trasferencia de conocimiento entre las entidades, la mejora de las situaciones de las entidades en situación de crisis y la dotación de programas de aprendizaje abiertos y multidisciplinares que resuelvan las necesidades crecientes de la ESS. Es especialmente importante favorecer con estas acciones la incorporación efectiva de las mujeres en todos los niveles de la ESS, así como el apoyo a las iniciativas mayoritariamente conformadas por mujeres." },
      { legislation_process_id: 26, author_id: 505793, proposal_type: "proposal", terms_of_service: "1",
        tag_list: "Apoyo a la financiación de las entidades de la ESS",
        title: "Creación de un Fondo Rotatorio. ",
        summary: "Esta medida pertenece a la línea de actuación: apoyo a la financiación de las entidades de la ESS.",
        description: "La Línea de actuación de esta acción pretende ofrecer respuesta a las diversas necesidades existentes de las entidades de la ESS. Se prevén diversos tipos de instrumentos: municipales, público-privados e instrumentos privados, todos ellos coordinados" },
      { legislation_process_id: 26, author_id: 505793, proposal_type: "proposal", terms_of_service: "1",
        tag_list: "Apoyo a la financiación de las entidades de la ESS",
        title: "Impulso al desarrollo de instrumentos que potencien el ahorro de proximidad y que financien iniciativas de ESS ligadas al territorio.",
        summary: "Esta medida pertenece a la línea de actuación: apoyo a la financiación de las entidades de la ESS.",
        description: "La Línea de actuación de esta acción pretende ofrecer respuesta a las diversas necesidades existentes de las entidades de la ESS. Se prevén diversos tipos de instrumentos: municipales, público-privados e instrumentos privados, todos ellos coordinados" },
      { legislation_process_id: 26, author_id: 505793, proposal_type: "proposal", terms_of_service: "1",
        tag_list: "Apoyo a la financiación de las entidades de la ESS",
        title: "Firma de convenios con entidades financieras de la ESS y sociedades de garantía recíproca.",
        summary: "Esta medida pertenece a la línea de actuación: apoyo a la financiación de las entidades de la ESS.",
        description: "La Línea de actuación de esta acción pretende ofrecer respuesta a las diversas necesidades existentes de las entidades de la ESS. Se prevén diversos tipos de instrumentos: municipales, público-privados e instrumentos privados, todos ellos coordinados" },
      { legislation_process_id: 26, author_id: 505793, proposal_type: "proposal", terms_of_service: "1",
        tag_list: "Apoyo a la financiación de las entidades de la ESS",
        title: "Incorporación de los instrumentos de finanzas éticas en las prácticas financieras del Ayuntamiento.",
        summary: "Esta medida pertenece a la línea de actuación: apoyo a la financiación de las entidades de la ESS.",
        description: "La Línea de actuación de esta acción pretende ofrecer respuesta a las diversas necesidades existentes de las entidades de la ESS. Se prevén diversos tipos de instrumentos: municipales, público-privados e instrumentos privados, todos ellos coordinados" },
      { legislation_process_id: 26, author_id: 505793, proposal_type: "proposal", terms_of_service: "1",
        tag_list: "Apoyo a los procesos de intercooperación de la ESS",
        title: "Apoyo a las acciones fomentadas por las entidades representativas de la ESS para la  articulación de proyectos de intercooperación entre sus asociadas.",
        summary: "Esta medida pertenece a la línea de actuación: apoyo a los procesos de intercooperación de la ESS.",
        description: "La Línea de actuación  de esta acción establece reforzar procesos de articulación de segundo y ulterior grado por parte de las iniciativas de la ESS, fortaleciendo las fórmulas estables de cooperación empresarial existentes y promoviendo la creación de nuevas. El objetivo es favorecer el crecimiento alcanzando mejores economías de escala, ampliar la oferta de bienes y servicios mejorando en la cadena de valor a través de la cooperación y el intercambio de conocimiento sectorial, favorecer la diversificación sectorial de las empresas de ESS y fortalecer, a través del ahorro de costes, la posición de la ESS dentro de determinados sectores." },
      { legislation_process_id: 26, author_id: 505793, proposal_type: "proposal", terms_of_service: "1",
        tag_list: "Apoyo a la transformación y transmisión de empresas mercantiles en entidades de ESS",
        title: "Elaboración de un inventario abierto de empresas existentes susceptibles de ser transformadas (empresas en crisis, traspasos, jubilaciones, etc.).",
        summary: "Esta medida pertenece a la línea de actuación: apoyo a la transformación y transmisión de empresas mercantiles en entidades de ESS.",
        description: "La Línea de actuación de esta acción establece  facilitar mecanismos para la conversión de empresas mercantiles en empresas de ESS, o con prácticas cercanas o potencialmente asumibles a las que representa la ESS. Tiene por objeto tanto la modificación de la fórmula jurídica como la adaptación y apropiación de modelos de organización democráticos y horizontales, característicos de la ESS." },
      { legislation_process_id: 26, author_id: 505793, proposal_type: "proposal", terms_of_service: "1",
        tag_list: "Apoyo a la transformación y transmisión de empresas mercantiles en entidades de ESS",
        title: "Acciones de información y sensibilización dirigidas a las empresas  existentes para su transformación en entidades de ESS. ",
        summary: "Esta medida pertenece a la línea de actuación: apoyo a la transformación y transmisión de empresas mercantiles en entidades de ESS.",
        description: "La Línea de actuación de esta acción establece  facilitar mecanismos para la conversión de empresas mercantiles en empresas de ESS, o con prácticas cercanas o potencialmente asumibles a las que representa la ESS. Tiene por objeto tanto la modificación de la fórmula jurídica como la adaptación y apropiación de modelos de organización democráticos y horizontales, característicos de la ESS." },
      { legislation_process_id: 26, author_id: 505793, proposal_type: "proposal", terms_of_service: "1",
        tag_list: "Programa de articulación entre autónomos\\/as comunidades de bienes sociedades limitadas y otras fórmulas empresariales a través de la ESS",
        title: "Acciones de sensibilización en ESS dirigidas a autónomos/as, comunidades de bienes, S.L. y otras fórmulas empresariales.",
        summary: "Esta medida pertenece a la línea de actuación: programa de articulación entre autónomos/as, comunidades de bienes, sociedades limitadas y otras fórmulas empresariales a través de la ESS.",
        description: "La Línea de actuación de esta acción establece fomentar la articulación a través de fórmulas de ESS de realidades microempresariales, principalmente de autónomos/as. Las fórmulas de ESS son un instrumento idóneo para avanzar en la mejora de las condiciones de producción de muchas realidades microempresariales ya sea por el lado de la integración, mancomunando servicios comunes o estableciendo sinergias para alcanzar más y mejor clientela." },
      { legislation_process_id: 26, author_id: 505793, proposal_type: "proposal", terms_of_service: "1",
        tag_list: "Programa de articulación entre autónomos\\/as comunidades de bienes sociedades limitadas y otras fórmulas empresariales a través de la ESS",
        title: "Línea de apoyo a la creación de entidades de ESS que aglutinan a otro tipo de empresas o a profesionales independientes.",
        summary: "Esta medida pertenece a la línea de actuación: programa de articulación entre autónomos/as, comunidades de bienes, sociedades limitadas y otras fórmulas empresariales a través de la ESS.",
        description: "La Línea de actuación de esta acción establece fomentar la articulación a través de fórmulas de ESS de realidades microempresariales, principalmente de autónomos/as. Las fórmulas de ESS son un instrumento idóneo para avanzar en la mejora de las condiciones de producción de muchas realidades microempresariales ya sea por el lado de la integración, mancomunando servicios comunes o estableciendo sinergias para alcanzar más y mejor clientela." },
      { legislation_process_id: 26, author_id: 505793, proposal_type: "proposal", terms_of_service: "1",
        tag_list: "Impulso de agrupaciones\\/clústers sectoriales de ESS y fomento de la participación en los clústers económicos que se impulsen desde el Ayuntamiento",
        title: "Detección de oportunidades de desarrollo económico para la selección de ámbitos productivos que puedan orientar el impulso de nuevas agrupaciones y clústeres.",
        summary: "Esta medida pertenece a la línea de actuación: impulso de agrupaciones y Clústers sectoriales de ESS y fomento de la participación en los clústers económicos que se impulsen desde el Ayuntamiento.",
        description: "La Línea de actuación de esta acción establece mejorar la profesionalización, competitividad y eficiencia de las entidades de la ESS e impulsar la innovación y el desarrollo de tejido productivo en sectores clave. Los sectores estarán definidos a partir de su capacidad de innovación, su potencial sostenibilidad y su valor añadido. Esta línea de actuación está muy vinculada a las oficinas de ESS y el servicio de dinamización. Las agrupaciones y clusters se apoyan en servicios de acompañamiento, incubación y formación e incorporan otros procesos más innovadores de intercambio y producción de conocimiento sectorial, con líneas más dirigidas a la investigación y a la cocreación de bienes y servicios con usuarios y usuarias." }
    ]
    puts "Creating #{legislation_proposals.count} Legislation::Proposals ⚙️"
    legislation_proposals.each do |legislation_proposal|
      Legislation::Proposal.create!(legislation_proposal)
    end
    puts "Created #{Legislation::Proposal.where('created_at >= ?', DateTime.now - 1.minutes).count} Legislation::Proposals ✅"
  end

  desc "Copy old debate comments to correspondig new questions"
  task debate_comments_to_questions: :environment do
    require "migrations/legislation_comments_migration"
    LegislationCommentsMigration.new.migrate_data
  end
end
