FactoryBot.define do
  factory :machine_learning_job do
    association :user, factory: :user
    script { "script.py" }
    started_at { Time.current }
    finished_at { nil }
    error { nil }
  end

  factory :machine_learning_info do
    kind { "tags" }
    generated_at { Time.current }
    script { "script.py" }
  end

  factory :ml_summary_comment do
    body { "Summary comment generated by Machine Learning" }
  end
end
