---
EnableDefaultLinters: false
exclude:
  - '**/vendor/**/*'
  - 'lib/capistrano/templates/*'
linters:
  AllowedScriptType:
    enabled: true
  ClosingErbTagIndent:
    enabled: true
  CommentSyntax:
    enabled: true
  ErbSafety:
    enabled: true
    exclude:
      - app/components/budgets/investments/content_blocks_component.html.erb
      - app/components/layout/cookies_consent/vendors/scripts_component.html.erb
      - app/components/layout/footer_component.html.erb
      - app/components/layout/social_component.html.erb
      - app/components/layout/subnavigation_component.html.erb
      - app/components/layout/top_links_component.html.erb
      - app/views/admin/site_customization/content_blocks/index.html.erb
      - app/views/layouts/application.html.erb
      - app/views/layouts/dashboard.html.erb
      - app/views/layouts/devise.html.erb
  ExtraNewline:
    enabled: true
  FinalNewline:
    enabled: true
  NoJavascriptTagHelper:
    enabled: true
  ParserErrors:
    enabled: true
  RightTrim:
    enabled: true
  SpaceAroundErbTag:
    enabled: true
  SpaceIndentation:
    enabled: true
  SpaceInHtmlTag:
    enabled: true
  TrailingWhitespace:
    enabled: true
  Rubocop:
    enabled: true
    rubocop_config:
      inherit_from:
        - .rubocop.yml
      Layout/LineLength:
        Enabled: false
      Layout/TrailingEmptyLines:
        Enabled: false
      Lint/UselessAssignment:
        Enabled: false
      Rails/HttpStatus:
        Enabled: true
        Exclude:
          - app/views/dashboard/*
      Rails/OutputSafety:
        Enabled: false
