service: consuldemocracy
image: consuldemocracy-app

servers:
  web:
    - vps2583611.fastwebserver.de

builder:
  arch: amd64

accessories:
  db:
    image: postgres:13.16
    host: db
    port: 5432
    env:
      clear:
        POSTGRES_USER: postgres
      secret:
        - POSTGRES_PASSWORD
    directories:
      - db_data:/var/lib/postgresql/data

env:
  secret:
    - SECRET_KEY_BASE
    - POSTGRES_PASSWORD
  clear:
    DB_HOST: db
    PGUSER: postgres
    PGPASSWORD: password
