local:
  service: TenantDisk
  root: <%= Rails.root.join("storage") %>

test:
  service: TenantDisk
  root: <%= Rails.root.join("tmp/storage") %>

# amazon:
#   service: S3
#   access_key_id: <%= Rails.application.secrets.dig(:s3, :access_key_id) %>
#   secret_access_key: <%= Rails.application.secrets.dig(:s3, :secret_access_key) %>
#   region: <%= Rails.application.secrets.dig(:s3, :region) %>
#   bucket: <%= Rails.application.secrets.dig(:s3, :bucket) %>

# Remember not to checkin your GCS keyfile to a repository
# google:
#   service: GCS
#   project: <%= Rails.application.secrets.dig(:gcs, :project) %>
#   credentials: <%= Rails.root.join(Rails.application.secrets.dig(:gcs, :credentials).to_s) %>
#   bucket: <%= Rails.application.secrets.dig(:gcs, :bucket) %>

# mirror:
#   service: Mirror
#   primary: local
#   mirrors: [ amazon, google, microsoft ]
