load Rails.root.join("db", "pages", "welcome_level_three_verified.rb")
load Rails.root.join("db", "pages", "welcome_level_two_verified.rb")
load Rails.root.join("db", "pages", "welcome_not_verified.rb")
load Rails.root.join("db", "pages", "accessibility.rb")
load Rails.root.join("db", "pages", "conditions.rb")
load Rails.root.join("db", "pages", "privacy.rb")
load Rails.root.join("db", "pages", "faq.rb")
load Rails.root.join("db", "pages", "census_terms.rb")
