require 'rails_helper'

feature 'Users' do

  background do
    login_as_manager
  end

  scenario 'Create a level 3 user with email from scratch' do
    visit management_document_verifications_path
    fill_in 'document_verification_document_number', with: '12345678Z'
    click_button 'Check'

    expect(page).to have_content "Please introduce the email used on the account"

    click_link 'Create a new account'

    fill_in 'user_username', with: 'pepe'
    fill_in 'user_email', with: 'pepe@gmail.com'
    select_date "31-December-#{valid_date_of_birth_year}", from: 'user_date_of_birth'
    fill_in 'user_lastname', with: 'mirza'
    fill_in 'user_firstname', with: 'zuliani'
    fill_in 'user_postal_code', with: '11000'

    click_button 'Create user'

    expect(page).to have_content "We have sent an email"
    expect(page).not_to have_content "Autogenerated password is"

    user = User.find_by(email: 'pepe@gmail.com')

    expect(user).to be_level_three_verified
    expect(user).to be_residence_verified
    expect(user).not_to be_confirmed
    expect(user.date_of_birth).to have_content Date.new(valid_date_of_birth_year, 12, 31)

    sent_token = /.*confirmation_token=(.*)".*/.match(ActionMailer::Base.deliveries.last.body.to_s)[1]
    visit user_confirmation_path(confirmation_token: sent_token)

    expect(page).to have_content "Confirming the account with email"

    fill_in 'user_password', with: '12345678'
    fill_in 'user_password_confirmation', with: '12345678'

    click_button 'Confirm'

    expect(user.reload).to be_confirmed

    expect(page).to have_content "Your account has been confirmed."
  end

  scenario 'Create a level 3 user without email from scratch' do
    visit management_document_verifications_path
    fill_in 'document_verification_document_number', with: '12345678Z'
    click_button 'Check'

    expect(page).to have_content "Please introduce the email used on the account"

    click_link 'Create a new account'

    fill_in 'user_username', with: 'Kelly Sue'
    fill_in 'user_email', with: ''
    select_date "31-December-#{valid_date_of_birth_year}", from: 'user_date_of_birth'
    fill_in 'user_lastname', with: 'mirza'
    fill_in 'user_firstname', with: 'zuliani'
    fill_in 'user_postal_code', with: '11000'

    click_button 'Create user'

    expect(page).not_to have_content "We have sent an email"
    expect(page).to have_content "Autogenerated password is"

    user = User.find_by(username: 'Kelly Sue')

    expect(user).to be_level_three_verified
    expect(user).to be_residence_verified
    expect(user).to be_confirmed
    expect(user.date_of_birth).to have_content Date.new(valid_date_of_birth_year, 12, 31)
  end

end
