name: production assets
on:
  push:
    branches:
      - master
  pull_request:
    branches-ignore:
      - i18n_master

permissions:
  contents: read

jobs:
  production_assets:
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    env:
      BUNDLE_WITHOUT: "development:test"
    steps:
      - uses: actions/checkout@v7
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Setup NPM
        uses: actions/setup-node@v7
        with:
          cache: "npm"
          node-version-file: ".node-version"
      - name: Install node packages
        run: npm clean-install
      - name: Copy secrets and database files
        run: for i in config/*.example; do cp "$i" "${i/.example}"; done
      - name: Compile production assets
        run: RAILS_ENV=production SECRET_KEY_BASE=precompile_dummy_key_for_ci_only bundle exec rake assets:precompile > /dev/null 2>&1
